steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    id: "Build"

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mike-app:$SHORT_SHA', '.']
    id: "Docker Build"

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mike-app:$SHORT_SHA']
    id: "Docker Push"

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'mike-app', '--image', 'gcr.io/$PROJECT_ID/mike-app:$SHORT_SHA', '--region', 'us-central1']
    id: "Deploy"

images:
  - 'gcr.io/$PROJECT_ID/mike-app:$SHORT_SHA'
